"""Prometheus metrics — single registry shared across the app."""
from __future__ import annotations

from prometheus_client import CollectorRegistry, Counter, Gauge, Histogram

registry = CollectorRegistry()

# ── Data layer ────────────────────────────────────────────────────────────
trades_received_total = Counter(
    "trades_received_total",
    "Trades received from the Polymarket WebSocket/REST",
    labelnames=("source",),
    registry=registry,
)

ws_disconnects_total = Counter(
    "ws_disconnects_total",
    "WebSocket disconnect events",
    labelnames=("endpoint",),
    registry=registry,
)

# ── Tracking ──────────────────────────────────────────────────────────────
tracked_wallets_gauge = Gauge(
    "tracked_wallets",
    "Number of wallets currently being monitored",
    registry=registry,
)

tracked_trades_total = Counter(
    "tracked_trades_total",
    "Trades from tracked wallets persisted to DB",
    labelnames=("wallet",),
    registry=registry,
)

# ── Signals ───────────────────────────────────────────────────────────────
signals_generated_total = Counter(
    "signals_generated_total",
    "Signals generated by the engine",
    labelnames=("strategy",),
    registry=registry,
)

signals_rejected_total = Counter(
    "signals_rejected_total",
    "Signals rejected by the risk manager",
    labelnames=("strategy", "reason"),
    registry=registry,
)

signal_confidence = Histogram(
    "signal_confidence",
    "Confidence score distribution of generated signals",
    labelnames=("strategy",),
    buckets=(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
    registry=registry,
)

# ── Execution ─────────────────────────────────────────────────────────────
trades_executed_total = Counter(
    "trades_executed_total",
    "Trades executed (paper or live)",
    labelnames=("mode", "side"),
    registry=registry,
)

position_pnl_usd = Gauge(
    "position_pnl_usd",
    "Unrealized PnL per open position",
    labelnames=("market_id",),
    registry=registry,
)

realized_pnl_usd = Gauge(
    "realized_pnl_usd",
    "Cumulative realized PnL",
    registry=registry,
)

position_holding_seconds = Histogram(
    "position_holding_seconds",
    "Holding time for closed positions",
    buckets=(60, 300, 900, 3600, 7200, 14400, 28800, 86400, 172800),
    registry=registry,
)

# ── Risk ──────────────────────────────────────────────────────────────────
kill_switch_active = Gauge(
    "kill_switch_active",
    "1 if kill switch is engaged, 0 otherwise",
    registry=registry,
)
