wallets:
- address: '0xda985d751c682615ade741d4415b4917bd9de50b'
  label: null
  median_holding_min: 2.3
  n_trades: 30
  owner_address: null
  roi: 0.642
  sharpe: 0.555
  source: discovery_script
  win_rate: 0.733
- address: '0xe3e3939bbca17c9b93ad571b0d4900628ac53d1c'
  label: null
  median_holding_min: 2.6
  n_trades: 53
  owner_address: null
  roi: 1.3311
  sharpe: 0.466
  source: discovery_script
  win_rate: 0.83
- address: '0x2c3cd2e6131f823c9a418394cf12249a3bc64683'
  label: null
  median_holding_min: 3.0
  n_trades: 96
  owner_address: null
  roi: 0.4465
  sharpe: 0.326
  source: discovery_script
  win_rate: 0.5
- address: '0x6498f9eab8018b2d61fe0186bee145f53e4d8910'
  label: null
  median_holding_min: 87.1
  n_trades: 27
  owner_address: null
  roi: 0.4816
  sharpe: 0.25
  source: discovery_script
  win_rate: 0.667
- address: '0xeaca59cb5e10e0be128b005a0f84465d2ed80729'
  label: null
  median_holding_min: 0.6
  n_trades: 293
  owner_address: null
  roi: 0.2053
  sharpe: 0.197
  source: discovery_script
  win_rate: 0.563
- address: '0x8e4a02ff7248e0b7640dd42fb8dd14c65f7df43d'
  label: null
  median_holding_min: 52.5
  n_trades: 171
  owner_address: null
  roi: 0.9637
  sharpe: 0.149
  source: discovery_script
  win_rate: 0.614
