wallets:
- address: '0x1015bb260154f51e5f432cb0a3227c1619fcbac8'
  label: null
  median_holding_min: 2.0
  n_trades: 20
  owner_address: null
  roi: 0.5502
  sharpe: 0.671
  source: discovery_script
  win_rate: 0.65
- address: '0xc5ae17997c95b7fc4aa8aca84e782ad59edd1144'
  label: null
  median_holding_min: 3.8
  n_trades: 41
  owner_address: null
  roi: 1.0008
  sharpe: 0.393
  source: discovery_script
  win_rate: 0.756
- address: '0x76d4d4703add6e94cfdb1107f3d991d85ff2c512'
  label: null
  median_holding_min: 2.2
  n_trades: 72
  owner_address: null
  roi: 0.1516
  sharpe: 0.349
  source: discovery_script
  win_rate: 0.417
- address: '0x1ba2b1137313b248b03a9be40093b23d7e96d212'
  label: null
  median_holding_min: 62.0
  n_trades: 70
  owner_address: null
  roi: 0.1451
  sharpe: 0.321
  source: discovery_script
  win_rate: 0.443
- address: '0x5d5a68ba12cf0264ea2dab626d99abb9a71c4289'
  label: null
  median_holding_min: 3.3
  n_trades: 25
  owner_address: null
  roi: 0.9587
  sharpe: 0.244
  source: discovery_script
  win_rate: 0.36
