"""Signal dataclass — output of the signal engine."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum

from app.data.models import OrderSide


class SignalStatus(str, Enum):
    PENDING = "pending"         # waiting for risk manager
    APPROVED = "approved"       # risk manager approved, queued for execution
    REJECTED = "rejected"       # risk manager rejected
    EXECUTED = "executed"       # position opened
    EXPIRED = "expired"         # never executed within time limit


@dataclass(frozen=True)
class Signal:
    """A trade signal generated by a strategy."""

    signal_id: str
    strategy: str               # whale_copy | consensus | fade_late | momentum_odds
    market_id: str              # condition_id
    asset_id: str               # token_id (YES or NO outcome token)
    side: OrderSide             # BUY or SELL
    confidence: float           # 0.0 – 1.0
    entry_price: Decimal        # estimated fair entry price (0-1)
    size_pct: float             # fraction of capital to allocate
    tp_pct: float               # take-profit percentage gain
    sl_pct: float               # stop-loss percentage loss
    max_holding_minutes: int    # force-close after this many minutes
    source_wallet: str          # wallet address that triggered the signal
    timestamp: datetime         # when the signal was generated
    reason: str                 # human-readable explanation
    market_question: str = ""   # human-readable market name (optional)
    status: SignalStatus = SignalStatus.PENDING
    reject_reason: str = ""     # populated by risk manager on rejection
